//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioWebDAO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMISIONE
    {
        public int ID { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDPEDIDO { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
